export default function Head() {
  return (
    <>
      <title>sAId.</title>
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1"
      />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="./favicon.ico" />
      <meta name="description" content="sAId.fyi" />
      <link rel="apple-touch-icon" href="../public/logo192.png" />
    </>
  );
}
